backend:
  name: github
  repo: yte0/testpage
  branch: main
  base_url: https://cmsapitest1.herokuapp.com
  
site_url: https://yte0.github.io/testpage
local:  'no'
media_folder: public/img
publish_mode: editorial_workflow 
public_folder: img
logo_url: https://www.skde.no/img/logos/SKDE_sort.png
slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"
collections:
  - label: "Blog"
    name: "blog"
    description: "This is an optional text that is displayed below the label when viewing a collection"
    folder: "_post/blog"
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    create: true
    fields:
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Ingress", name: "ingress", widget: "text" }
      - { label: "Data", name: "data", widget: "file" }
      - { label: "Article Image", name: "thumbnail", widget: "image" }


  - label: "Blog in English"
    name: "english_posts"
    folder: "_posts/entries"
    create: true
    filter: {field: "language", value: "en"}
    fields:
      - {label: "Language", name: "language", widget: "select", options: ["en", "es"]}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Content", name: "body", widget: "markdown"}
  - label: "Blog en Español"
    name: "spanish_posts"
    folder: "_posts"
    create: true
    filter: {field: "language", value: "es"}
    fields:
      - {label: "Lenguaje", name: "language", widget: "select", options: ["en", "es"]}
      - {label: "Titulo", name: "title", widget: "string"}
      - {label: "Contenido", name: "body", widget: "markdown"}